/** Initial frame lens catalogue; saved administrator values take precedence. */
export const DEFAULT_FRAME_LENS_CONFIGURATION = {
  powerTypes: [
    {
      price: 0,
      badge: 'Most common',
      badgeColor: 'brand',
      autoAdvance: true,
      isActive: true,
      order: 0,
      id: 'single-vision',
      label: 'With Power',
      subtitle: 'Positive, Negative or Cylindrical',
      icon: 'Eye',
      iconBgColor: 'brand',
      requiresPrescription: true,
    },
    {
      price: 0,
      badge: 'BLU Screen lenses',
      badgeColor: 'brand',
      autoAdvance: true,
      isActive: true,
      order: 1,
      id: 'zero-power',
      label: 'Zero Power',
      subtitle: 'Blue light block for screen protection',
      icon: 'Monitor',
      iconBgColor: 'purple',
      requiresPrescription: false,
    },
    {
      price: 0,
      badge: '',
      badgeColor: 'brand',
      autoAdvance: true,
      isActive: true,
      order: 2,
      id: 'progressive',
      label: 'Progressive/Bifocals',
      subtitle: 'Two powers in one eye',
      icon: 'Layers',
      iconBgColor: 'blue',
      requiresPrescription: true,
    },
    {
      price: 0,
      badge: '',
      badgeColor: 'brand',
      autoAdvance: true,
      isActive: true,
      order: 3,
      id: 'frame-only',
      label: 'Frame Only',
      subtitle: 'With no lenses',
      icon: 'Square',
      iconBgColor: 'grey',
      requiresPrescription: false,
    },
  ],
  packageCategories: [
    {
      id: 'bestsellers',
      label: '⭐ Bestsellers',
      order: 0,
      isActive: true,
    },
    {
      id: 'work-friendly',
      label: '💻 Work Friendly',
      order: 1,
      isActive: true,
    },
    {
      id: 'high-power',
      label: '♾️ High Power',
      order: 2,
      isActive: true,
    },
    {
      id: 'colored',
      label: '👓 Colored',
      order: 3,
      isActive: true,
    },
    {
      id: 'all',
      label: '⚪ All',
      order: 4,
      isActive: true,
    },
  ],
  packages: [
    {
      id: 'anti-glare',
      name: 'Anti-Glare Premium',
      price: 0,
      features: ['Anti-Glare coating', 'Scratch resistant'],
      badge: 'Included',
      categories: ['bestsellers'],
      order: 0,
      description: 'Anti-Glare coating. Scratch resistant',
      imageUrl: '',
      isRecommended: false,
      isActive: true,
      powerTypes: ['single-vision', 'zero-power', 'progressive'],
      ribbonText: 'Free Lenses',
      ribbonColor: 'blue',
      warranty: '',
      mrp: 0,
      couponText: '',
      videoUrl: '',
      featureIcons: ['⚡', '🛡️'],
    },
    {
      id: 'blu-screen',
      name: 'BLU Screen Protection',
      price: 500,
      features: ['Blue light filtering', 'Anti-glare', 'Reduces eye strain'],
      badge: 'Screen favourite',
      categories: ['bestsellers', 'work-friendly'],
      order: 1,
      description: 'Blue light filtering. Anti-glare. Reduces eye strain',
      imageUrl: '',
      isRecommended: false,
      isActive: true,
      powerTypes: ['single-vision', 'zero-power', 'progressive'],
      ribbonText: '',
      ribbonColor: 'none',
      warranty: '',
      mrp: 500,
      couponText: '',
      videoUrl: '',
      featureIcons: ['⚡', '🛡️', '😇'],
    },
    {
      id: 'blu-thin',
      name: 'BLU Thin',
      price: 1200,
      features: ['Blue light filter', 'Thin lenses', 'Anti-glare'],
      badge: 'Best for powers ±3',
      categories: ['high-power', 'work-friendly'],
      order: 2,
      description: 'Blue light filter. Thin lenses. Anti-glare',
      imageUrl: '',
      isRecommended: false,
      isActive: true,
      powerTypes: ['single-vision', 'zero-power', 'progressive'],
      ribbonText: '',
      ribbonColor: 'none',
      warranty: '',
      mrp: 1200,
      couponText: '',
      videoUrl: '',
      featureIcons: ['⚡', '🛡️', '😇'],
    },
    {
      id: 'photochromic',
      name: 'Photochromic Comfort',
      price: 1500,
      features: ['Darkens in sunlight', 'UV 400 protection', 'Anti-glare'],
      badge: 'Outdoor ready',
      categories: ['colored'],
      order: 3,
      description: 'Darkens in sunlight. UV 400 protection. Anti-glare',
      imageUrl: '',
      isRecommended: false,
      isActive: true,
      powerTypes: ['single-vision', 'zero-power', 'progressive'],
      ribbonText: '',
      ribbonColor: 'none',
      warranty: '',
      mrp: 1500,
      couponText: '',
      videoUrl: '',
      featureIcons: ['⚡', '🛡️', '😇'],
    },
    {
      id: 'ultra-thin',
      name: 'Ultra Thin',
      price: 2500,
      features: ['Thinnest lenses', 'All coatings included', 'For high power'],
      badge: 'High power ±6',
      categories: ['high-power', 'colored'],
      order: 4,
      description: 'Thinnest lenses. All coatings included. For high power',
      imageUrl: '',
      isRecommended: false,
      isActive: true,
      powerTypes: ['single-vision', 'zero-power', 'progressive'],
      ribbonText: '',
      ribbonColor: 'none',
      warranty: '',
      mrp: 2500,
      couponText: '',
      videoUrl: '',
      featureIcons: ['⚡', '🛡️', '😇'],
    },
  ],
  prescriptionFields: [
    {
      key: 'sph',
      label: 'SPH',
      min: -20,
      max: 20,
      step: 0.25,
      scope: 'per-eye',
      required: true,
      fieldType: 'dropdown',
      placeholder: 'Select SPH',
      helpText: '',
      isActive: true,
      powerTypes: ['single-vision', 'progressive'],
    },
    {
      key: 'cyl',
      label: 'CYL',
      min: -10,
      max: 0,
      step: 0.25,
      scope: 'per-eye',
      required: false,
      fieldType: 'dropdown',
      placeholder: 'Select CYL',
      helpText: '',
      isActive: true,
      powerTypes: ['single-vision', 'progressive'],
    },
    {
      key: 'axis',
      label: 'Axis',
      min: 1,
      max: 180,
      step: 1,
      scope: 'per-eye',
      required: false,
      fieldType: 'dropdown',
      placeholder: 'Select Axis',
      helpText: '',
      isActive: true,
      powerTypes: ['single-vision', 'progressive'],
    },
    {
      key: 'add',
      label: 'ADD',
      min: 0.75,
      max: 3.5,
      step: 0.25,
      scope: 'per-eye',
      required: true,
      fieldType: 'dropdown',
      placeholder: 'Select ADD',
      helpText: '',
      isActive: true,
      powerTypes: ['progressive'],
    },
    {
      key: 'pd',
      label: 'PD',
      min: 50,
      max: 80,
      step: 1,
      scope: 'shared',
      required: true,
      fieldType: 'dropdown',
      placeholder: 'Select PD',
      helpText: '',
      isActive: true,
      powerTypes: ['single-vision', 'progressive'],
    },
  ],
  generalSettings: {
    uiText: {
      powerTitle: 'Select your Power Type:',
      lensesTitle: 'Select your lenses:',
      learnMore: 'Learn more ›',
      knowMore: 'Know more',
      included: 'Included',
      recommended: 'Recommended',
      continue: 'Continue',
      back: 'Back',
      total: 'Total',
      frame: 'Frame',
      lens: 'Lens',
      ready: 'Your lens selection is ready',
      manualTitle: 'Enter power manually',
      manualSubtitle: 'Use values from your latest eye prescription',
      uploadTitle: 'Upload prescription',
      uploadSubtitle: 'Choose an image or PDF of your prescription',
      rightEye: 'Right Eye (OD)',
      leftEye: 'Left Eye (OS)',
      emptyPower: 'No power types are available.',
      emptyPackages: 'No lenses in this category. Try another category.',
      requiredMessage: 'Complete all required fields using the allowed values.',
      chooseFile: 'Choose prescription file',
      dropFile: 'Drag a file here (up to 2 MB)',
    },
    drawerTitle: 'Select Lens Type',
    stepLabels: ['Power Type', 'Lenses', 'Add Power'],
    learnMoreUrl: '',
    showRunningTotal: true,
    ctaText: 'Add to Cart',
    noPrescriptionMessage: 'No prescription required for this selection.',
    autoAdvance: true,
  },
};
